name: Build MSI

on:
  push:
    branches:
      - Test

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '4.8' # Replace with the desired .NET version
    
    - name: Restore NuGet packages
      run: dotnet restore BlockUrlViaForms.sln
      
    - name: Build MSI
      run: dotnet msbuild /p:Configuration=Release BlockUrlViaForms.sln /t:Rebuild
      
    - name: Publish MSI artifact
      uses: actions/upload-artifact@v2
      with:
        name: MSI Package
        path: AppSetup/AgentSetup.msi
