name: dotnet package

on: [push]

jobs:
  build:

    runs-on: windows-latest
    strategy:
      matrix:
        dotnet-version: [ '4.8.x' ]

    steps:
      - uses: actions/checkout@v4
      - name: Setup dotnet
        uses: actions/setup-dotnet@v3
        with:
         dotnet-version: '4.8.x'
        
      - name: Install dependencies
        run: dotnet add package Newtonsoft.Json --version 13.0.1
