name: dot net package

on:  
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:  
  build:    
    runs-on: windows-latest

    steps:      
      - uses: actions/checkout@v2

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1

      - name: Setup NuGet
        uses: NuGet/setup-nuget@v1.0.5

      - name: Setup VSTest
        uses: darenm/Setup-VSTest@v1

      - name: Navigate to Workspace
        run: cd $GITHUB_WORKSPACE

      - name: Clean Build
        run: msbuild BlockUrlViaForms.sln /t:Clean

      - name: Build Solution
        run: msbuild BlockUrlViaForms.sln /t:build
        
      - name: Rebuild Solution
        run: msbuild BlockUrlViaForms.sln /t:rebuild
